export const REGISTER_REQUEST: 'REGISTER_REQUEST' = "REGISTER_REQUEST";
export const REGISTER_SUCCESS: 'REGISTER_SUCCESS' = "REGISTER_SUCCESS";
export const REGISTER_FAILED: 'REGISTER_FAILED' = "REGISTER_FAILED";

export const LOGIN_REQUEST: 'LOGIN_REQUEST' = "LOGIN_REQUEST";
export const LOGIN_SUCCESS: 'LOGIN_SUCCESS' = "LOGIN_SUCCESS";
export const LOGIN_FAILED: 'LOGIN_FAILED' = "LOGIN_FAILED";

export const FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST' = "FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_FAILED: 'FORGOT_PASSWORD_FAILED' = "FORGOT_PASSWORD_FAILED";
export const FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS' = "FORGOT_PASSWORD_SUCCESS";


export const LOAD_USER_REQUEST: 'LOAD_USER_REQUEST' = "LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS: 'LOAD_USER_SUCCESS' = "LOAD_USER_SUCCESS";
export const LOAD_USER_FAILED: 'LOAD_USER_FAILED' = "LOAD_USER_FAILED";


export const UPDATE_USER_REQUEST: 'UPDATE_USER_REQUEST' = "UPDATE_USER_REQUEST";
export const UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS' = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILED: 'UPDATE_USER_FAILED' = "UPDATE_USER_FAILED";

export const LOGOUT_REQUEST: 'LOGOUT_REQUEST' = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS: 'LOGOUT_SUCCESS' = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED: 'LOGOUT_FAILED' = "LOGOUT_FAILED";

export const REFRESH_TOKEN_REQUEST: 'REFRESH_TOKEN_REQUEST' = 'REFRESH_TOKEN_REQUEST';
export const REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS' = 'REFRESH_TOKEN_SUCCESS';
export const REFRESH_TOKEN_FAILED: 'REFRESH_TOKEN_FAILED' = 'REFRESH_TOKEN_FAILED';
